export const adsData: {
  adID:string,
  dealerID:string,
  description:string,
  imageID:string,
  fuel: string,
  transmission:string,  
}[] = [
{
adID:`2nd Try`,
dealerID:`KayWard`,
description:`Le Voyager lounge`,
imageID:`6025a923f6cf590004727ed4`,
fuel: ``,
transmission:``,
},
{
adID:`1765`,
dealerID:`RickVoller`,
description:`This is an amazing van, at a great price!`,
imageID:`6026e08c5229a600041af768`,
fuel: `diesel`,
transmission:`manual`,
},
{
adID:`1766`,
dealerID:`DodgyDave`,
description:`This van has been on many a voyage and is seeking its forever home.`,
imageID:`6026e0b45229a600041af76c`,
fuel: `diesel`,
transmission:`manual`,
},
{
adID:`1`,
dealerID:`DodgyDave`,
description:`This Beautiful flair 920le supplied to its original keeper in 2015 is in showroom condition. The winner of the MMM luxury motorhome of the year awards 2017. She boasts of many extras inc its champagne exterior paint.\nSome of its features include a coffee machine, 3x gel batteries with onboard 2000 watt inverter.\nShe has a 170l fuel tank and a 370l fresh water tank meaning you could go off the grid for many weeks at a time. Automatic suspension and an oyster 85cm satellite is just a few of the luxury items fitted to this incredibly well-kept machine.\nLike all RAC Approved used motorhomes from AMC Motorhomes, this vehicle comes with 12 Months MOT, Full Pre-Delivery Inspection, Full Mechanical Service, Full Habitation Inspection, Full Interior & Exterior Valet, Full Demonstration On Collection, Full HPI Certification. Being the UK's only RAC authorized used motorhome dealer, all our vans come with a minimum 6 Month RAC Warranty.`,
imageID:`6028e1a432c4f500041d7d4c`,
fuel: `diesel`,
transmission:`manual`,
},
{
adID:`2`,
dealerID:`DodgyDave`,
description:`AMC Motorhomes, the UK's number 1 builders of bespoke Airstreams and motorhomes is proud to be selling this RAC approved newly refurbished 1983 Airstream Sovereign Excella. This fully converted UK spec Airstream was built with a money no object approach, and wow, what a result! The interior was completely remade by AMC to incorporate a fixed rear bed with plenty of under bed storage. There's a good size wetroom with separate composting toilet and shower fed by a 200-litre water tank. Most of the power in this conversion comes from the monster 1000 Watts of solar that feed the Transporter Energy lithium batteries (currently the best on the market), with only the heating and hot water that are run by a Webasto Heater. The power management and split 3kw  Victron Inverters make this mobile home truly off-grid. A full-size fridge freezer is situated in the full-length Corion kitchen. LED lighting throughout, this Airstream simply must be seen to be fully appreciated. Full demonstration video supplied before collection. Delivery and site setup can be arranged however this will be extra. Full RAC warranty provided. AMC Motorhomes is the UK's only RAC Recommended used motorhome dealership. Finance available, and part exchange welcome. https://www.amcmotorcaravans.co.uk/used/ 01323 385017`,
imageID:`6028e1df32c4f500041d7d50`,
fuel: `petrol`,
transmission:`manual`,
},
{
adID:`3`,
dealerID:`DodgyDave`,
description:`A Rare 4x4 off-grid lithium powered Expedition vehicle, ideal for complete off-grid adventures using its bespoke lithium banks and solar to power its internal workings including induction hob, microwave oven and lighting amongst other unique features.`,
imageID:`6028e22232c4f500041d7d54`,
fuel: `petrol`,
transmission:`manual`,
},
{
adID:`4`,
dealerID:`DodgyDave`,
description:`RAC Approved used Burstner Elegance for sale from AMC Motorhomes. Comes with 12 Month MOT, Habitation service, Mechanical Service, Full Interior & Exterior Valet, Full Demonstration On Collection, Full HPI Certification and RAC warranty. AMC Motorhomes is the UK's only RAC Recommended used motorhome dealership. Finance available, and part exchange welcome. httpswww.amcmotorcaravans.co.ukused 01323 385017`,
imageID:`6028e26432c4f500041d7d58`,
fuel: `petrol`,
transmission:`manual`,
},
{
adID:`4`,
dealerID:`DodgyDave`,
description:`RAC Approved used Mobility Motorhome for sale from AMC Motorhomes. Comes with 12 Month MOT, Habitation service, Mechanical Service, Full Interior & Exterior Valet, Full Demonstration On Collection, Full HPI Certification and RAC warranty. AMC Motorhomes is the UK's only RAC Recommended used motorhome dealership. Finance available, and part exchange welcome. https://www.amcmotorcaravans.co.uk/used/ 01323 385017`,
imageID:`6028e28a32c4f500041d7d5c`,
fuel: `petrol`,
transmission:`automatic`,
},
{
adID:`9`,
dealerID:`DodgyDave`,
description:`RAC Approved used Bolero 722 FB for sale from AMC Motorhomes. Comes with 12 Month MOT, Habitation service, Mechanical Service, Full Interior & Exterior Valet, Full Demonstration On Collection, Full HPI Certification. Being the UK's only RAC recommended used motorhome dealer, all our vans come with a minimum 6 Month RAC Warranty. Finance available, and part exchange welcome.\n\nThe Swift Bolero 722 FB is a modern full-width end washroom layout that features a fixed french bed over storage and generous storage cupboards, wardrobes and drawers. The front lounge benefits from extra light and the feeling of space from the large skylight mounted in the low profile roof pod. The Swift Bolero 722FB has swivel cab seats and two side-facing settees in the lounge area which make a comfortable space for 6 people to dine and socialise. When evening comes and it is time to turn in the settees pull together to make a large double bed. Our Swift Bolero 722FB motorhome for sale features; 4 Berth 2 Seatbelts Fixed French Bed over Storage Lounge with Side Facing Settees L-shaped Kitchen Full Oven and Grill 3 Burner Gas and 1 Plate Mains Hob Sink Microwave Fridge Freezer with Separate Freezer Hot and Cold Water Blown Air Heating System Digital Heating Controller Full Width Rear Washroom Electric Flush Cassette Toilet Wash Basin Separate Shower Swivel Cab Seats Cab Blinds Electric Windows Cab Air Conditioning Cruise Control Driver and Passenger Airbags Electric Mirrors Entertainment System USB Digital TV Aerial Awning Flyscreen Door Cycle Rack Tow Bar Twin Lens Reverse Camera https://www.amcmotorcaravans.co.uk/used/ 01323 385017`,
imageID:`6028e3c832c4f500041d7d60`,
fuel: `petrol`,
transmission:`automatic`,
}]
export const dealersData:{
  dealerID:string,
  dealership:string,
  address:string,
  email:string,  
}[] = [
{
dealerID:`KayWard`,
dealership:`Littlehampton Best Motorhomes`,
address:`10 The Street, Littlehampton, LH13 2AC`,
email:`kay_lbmh@hotmail.com`,
},
{
dealerID:`KayWard`,
dealership:`Worthing Best Campervans`,
address:`15 The Street, Worthing, PO13 2AC`,
email:`kay_wbcv@hotmail.com`,
},
{
dealerID:`RickVoller`,
dealership:`Worthing Value Campervans`,
address:`17 The Street, Worthing, PO13 2AC`,
email:`rick_wvcv@hotmail.com`,
},
{
dealerID:`RickVoller`,
dealership:`Ricks renovations`,
address:`199 Top Road, Portsmouth`,
email:`rick@ms.com`,
},
{
dealerID:`DodgyDave`,
dealership:`Dave's Deals`,
address:`199 Top Road, Southhampton`,
email:`dave@gmail.com`,
},
{
dealerID:`1613160588681-van1.jpg`,
dealership:`6026e08c5229a600041af768`,
address:``,
email:``,
},
{
dealerID:`1613160628027-van2.jpg`,
dealership:`6026e0b45229a600041af76c`,
address:``,
email:``,
},
{
dealerID:`1613291940646-15586852515ce7a6430bf0c_dsc04142.jpg`,
dealership:`6028e1a432c4f500041d7d4c`,
address:``,
email:``,
},
{
dealerID:`1613291999452-16121114496016de5995765_whatsapp-image-2021-01-31-at-10.50.11-2-.jpeg`,
dealership:`6028e1df32c4f500041d7d50`,
address:``,
email:``,
},
{
dealerID:`1613292066685-16045838065fa4017e7613d_img-0315.jpg`,
dealership:`6028e22232c4f500041d7d54`,
address:``,
email:``,
},
{
dealerID:`1613292132189-16007736725f69de283f1fc_dsc08711.jpg`,
dealership:`6028e26432c4f500041d7d58`,
address:``,
email:``,
},
{
dealerID:`1613292170590-16082090715fdb52af954a3_dsc08924.jpg`,
dealership:`6028e28a32c4f500041d7d5c`,
address:``,
email:``,
},
{
dealerID:`1613292488270-15910925775ed6256193850_whatsapp-image-2020-06-02-at-08.54.51.jpeg`,
dealership:`6028e3c832c4f500041d7d60`,
address:``,
email:``,
},
{
dealerID:`1613292533979-15910925775ed6256193850_whatsapp-image-2020-06-02-at-08.54.51 (1).jpeg`,
dealership:`6028e3f532c4f500041d7d64`,
address:``,
email:``,
}]